<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Removing Duplicates**

Estimated time needed: **30** minutes

## Introduction

In this lab, you will focus on data wrangling, an important step in preparing data for analysis. Data wrangling involves cleaning and organizing data to make it suitable for analysis. One key task in this process is removing duplicate entries, which are repeated entries that can distort analysis and lead to inaccurate conclusions.

## Objectives

In this lab you will perform the following:

1. Identify duplicate rows  in the dataset.
2. Use suitable techniques to remove duplicate rows and verify the removal.
3. Summarize how to handle missing values appropriately.
4. Use ConvertedCompYearly to normalize compensation data.

### Install the Required Libraries

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 199.1 MB/s eta 0:00:00
Downloading numpy-2.2.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 196.6 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.2.4 pandas-2.2.3 tzdata-2025.2

### Step 1: Import Required Libraries

In [11]:
import pandas as pd
import numpy as np

### Step 2: Load the Dataset into a DataFrame

load the dataset using pd.read_csv()

In [3]:
# Define the URL of the dataset
file_path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows to ensure it loaded correctly
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

**Note: If you are working on a local Jupyter environment, you can use the URL directly in the <code>pandas.read_csv()</code>  function as shown below:**

#df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv")

### Step 3: Identifying Duplicate Rows

**Task 1: Identify Duplicate Rows**
  1. Count the number of duplicate rows in the dataset.
  2. Display the first few duplicate rows to understand their structure.

In [6]:
## Write your code here
df_duplicates = df[df.duplicated()]
print(len(df_duplicates))
df_duplicates.head()

0

Empty DataFrame
Columns: [ResponseId, MainBranch, Age, Employment, RemoteWork, Check, CodingActivities, EdLevel, LearnCode, LearnCodeOnline, TechDoc, YearsCode, YearsCodePro, DevType, OrgSize, PurchaseInfluence, BuyNewTool, BuildvsBuy, TechEndorse, Country, Currency, CompTotal, LanguageHaveWorkedWith, LanguageWantToWorkWith, LanguageAdmired, DatabaseHaveWorkedWith, DatabaseWantToWorkWith, DatabaseAdmired, PlatformHaveWorkedWith, PlatformWantToWorkWith, PlatformAdmired, WebframeHaveWorkedWith, WebframeWantToWorkWith, WebframeAdmired, EmbeddedHaveWorkedWith, EmbeddedWantToWorkWith, EmbeddedAdmired, MiscTechHaveWorkedWith, MiscTechWantToWorkWith, MiscTechAdmired, ToolsTechHaveWorkedWith, ToolsTechWantToWorkWith, ToolsTechAdmired, NEWCollabToolsHaveWorkedWith, NEWCollabToolsWantToWorkWith, NEWCollabToolsAdmired, OpSysPersonal use, OpSysProfessional use, OfficeStackAsyncHaveWorkedWith, OfficeStackAsyncWantToWorkWith, OfficeStackAsyncAdmired, OfficeStackSyncHaveWorkedWith, OfficeStackSyncWantToWorkWith, OfficeStackSyncAdmired, AISearchDevHaveWorkedWith, AISearchDevWantToWorkWith, AISearchDevAdmired, NEWSOSites, SOVisitFreq, SOAccount, SOPartFreq, SOHow, SOComm, AISelect, AISent, AIBen, AIAcc, AIComplex, AIToolCurrently Using, AIToolInterested in Using, AIToolNot interested in Using, AINextMuch more integrated, AINextNo change, AINextMore integrated, AINextLess integrated, AINextMuch less integrated, AIThreat, AIEthics, AIChallenges, TBranch, ICorPM, WorkExp, Knowledge_1, Knowledge_2, Knowledge_3, Knowledge_4, Knowledge_5, Knowledge_6, Knowledge_7, Knowledge_8, Knowledge_9, Frequency_1, Frequency_2, Frequency_3, TimeSearching, TimeAnswering, Frustration, ProfessionalTech, ProfessionalCloud, ProfessionalQuestion, ...]
Index: []

[0 rows x 114 columns]

### Step 4: Removing Duplicate Rows

**Task 2: Remove Duplicates**
   1. Remove duplicate rows from the dataset using the drop_duplicates() function.
2. Verify the removal by counting the number of duplicate rows after removal .

In [9]:
## Write your code here
df_no_duplicates = df.drop_duplicates()
print(len(df))
print(len(df_no_duplicates))
df = df_no_duplicates

65437
65437

### Step 5: Handling Missing Values

**Task 3: Identify and Handle Missing Values**
   1. Identify missing values for all columns in the dataset.
   2. Choose a column with significant missing values (e.g., EdLevel) and impute with the most frequent value.

In [20]:
## Write your code here
df.replace("?", np.nan, inplace=True)
missing_data = df.isnull()
print(missing_data.head())

# Count missing values for each column
for column in missing_data.columns.values.tolist():
    print(missing_data[column].value_counts(), "/n")

# Replace EdLevel with most frequent value
common_value = df["EdLevel"].value_counts().idxmax()
df["EdLevel"] = df["EdLevel"].replace(np.nan, common_value)
missing_EdLevel = df["EdLevel"].isnull()
print(missing_EdLevel.value_counts())

   ResponseId  MainBranch    Age  Employment  RemoteWork  Check  \
0       False       False  False       False       False  False
1       False       False  False       False       False  False
2       False       False  False       False       False  False
3       False       False  False       False        True  False
4       False       False  False       False        True  False

   CodingActivities  EdLevel  LearnCode  LearnCodeOnline  ...  JobSatPoints_6  \
0             False    False      False             True  ...            True
1             False    False      False            False  ...           False
2             False    False      False            False  ...            True
3              True    False      False            False  ...            True
4              True    False      False            False  ...            True

   JobSatPoints_7  JobSatPoints_8  JobSatPoints_9  JobSatPoints_10  \
0            True            True            True             True
1           False           False           False            False
2            True            True            True             True
3            True            True            True             True
4            True            True            True             True

   JobSatPoints_11  SurveyLength  SurveyEase  ConvertedCompYearly  JobSat
0             True          True        True                 True    True
1            False          True        True                 True    True
2             True         False       False                 True    True
3             True         False       False                 True    True
4             True         False       False                 True    True

[5 rows x 114 columns]
ResponseId
False    65437
Name: count, dtype: int64 /n
MainBranch
False    65437
Name: count, dtype: int64 /n
Age
False    65437
Name: count, dtype: int64 /n
Employment
False    65437
Name: count, dtype: int64 /n
RemoteWork
False    54806
True     10631
Name: count, dtype: int64 /n
Check
False    65437
Name: count, dtype: int64 /n
CodingActivities
False    54466
True     10971
Name: count, dtype: int64 /n
EdLevel
False    65437
Name: count, dtype: int64 /n
LearnCode
False    60488
True      4949
Name: count, dtype: int64 /n
LearnCodeOnline
False    49237
True     16200
Name: count, dtype: int64 /n
TechDoc
False    40897
True     24540
Name: count, dtype: int64 /n
YearsCode
False    59869
True      5568
Name: count, dtype: int64 /n
YearsCodePro
False    51610
True     13827
Name: count, dtype: int64 /n
DevType
False    59445
True      5992
Name: count, dtype: int64 /n
OrgSize
False    47480
True     17957
Name: count, dtype: int64 /n
PurchaseInfluence
False    47406
True     18031
Name: count, dtype: int64 /n
BuyNewTool
False    45181
True     20256
Name: count, dtype: int64 /n
BuildvsBuy
False    43358
True     22079
Name: count, dtype: int64 /n
TechEndorse
False    43668
True     21769
Name: count, dtype: int64 /n
Country
False    58930
True      6507
Name: count, dtype: int64 /n
Currency
False    46684
True     18753
Name: count, dtype: int64 /n
CompTotal
False    33740
True     31697
Name: count, dtype: int64 /n
LanguageHaveWorkedWith
False    59745
True      5692
Name: count, dtype: int64 /n
LanguageWantToWorkWith
False    55752
True      9685
Name: count, dtype: int64 /n
LanguageAdmired
False    50872
True     14565
Name: count, dtype: int64 /n
DatabaseHaveWorkedWith
False    50254
True     15183
Name: count, dtype: int64 /n
DatabaseWantToWorkWith
False    42558
True     22879
Name: count, dtype: int64 /n
DatabaseAdmired
False    38557
True     26880
Name: count, dtype: int64 /n
PlatformHaveWorkedWith
False    42366
True     23071
Name: count, dtype: int64 /n
PlatformWantToWorkWith
False    34532
True     30905
Name: count, dtype: int64 /n
PlatformAdmired
True     34060
False    31377
Name: count, dtype: int64 /n
WebframeHaveWorkedWith
False    45161
True     20276
Name: count, dtype: int64 /n
WebframeWantToWorkWith
False    38535
True     26902
Name: count, dtype: int64 /n
WebframeAdmired
False    34943
True     30494
Name: count, dtype: int64 /n
EmbeddedHaveWorkedWith
True     43223
False    22214
Name: count, dtype: int64 /n
EmbeddedWantToWorkWith
True     47837
False    17600
Name: count, dtype: int64 /n
EmbeddedAdmired
True     48704
False    16733
Name: count, dtype: int64 /n
MiscTechHaveWorkedWith
False    39443
True     25994
Name: count, dtype: int64 /n
MiscTechWantToWorkWith
False    32964
True     32473
Name: count, dtype: int64 /n
MiscTechAdmired
True     35841
False    29596
Name: count, dtype: int64 /n
ToolsTechHaveWorkedWith
False    52482
True     12955
Name: count, dtype: int64 /n
ToolsTechWantToWorkWith
False    46084
True     19353
Name: count, dtype: int64 /n
ToolsTechAdmired
False    43997
True     21440
Name: count, dtype: int64 /n
NEWCollabToolsHaveWorkedWith
False    57592
True      7845
Name: count, dtype: int64 /n
NEWCollabToolsWantToWorkWith
False    52087
True     13350
Name: count, dtype: int64 /n
NEWCollabToolsAdmired
False    50711
True     14726
Name: count, dtype: int64 /n
OpSysPersonal use
False    58174
True      7263
Name: count, dtype: int64 /n
OpSysProfessional use
False    52973
True     12464
Name: count, dtype: int64 /n
OfficeStackAsyncHaveWorkedWith
False    48093
True     17344
Name: count, dtype: int64 /n
OfficeStackAsyncWantToWorkWith
False    38966
True     26471
Name: count, dtype: int64 /n
OfficeStackAsyncAdmired
False    37204
True     28233
Name: count, dtype: int64 /n
OfficeStackSyncHaveWorkedWith
False    55545
True      9892
Name: count, dtype: int64 /n
OfficeStackSyncWantToWorkWith
False    46711
True     18726
Name: count, dtype: int64 /n
OfficeStackSyncAdmired
False    44712
True     20725
Name: count, dtype: int64 /n
AISearchDevHaveWorkedWith
False    44453
True     20984
Name: count, dtype: int64 /n
AISearchDevWantToWorkWith
False    36701
True     28736
Name: count, dtype: int64 /n
AISearchDevAdmired
False    35543
True     29894
Name: count, dtype: int64 /n
NEWSOSites
False    60286
True      5151
Name: count, dtype: int64 /n
SOVisitFreq
False    59536
True      5901
Name: count, dtype: int64 /n
SOAccount
False    59560
True      5877
Name: count, dtype: int64 /n
SOPartFreq
False    45237
True     20200
Name: count, dtype: int64 /n
SOHow
False    58962
True      6475
Name: count, dtype: int64 /n
SOComm
False    59163
True      6274
Name: count, dtype: int64 /n
AISelect
False    60907
True      4530
Name: count, dtype: int64 /n
AISent
False    45873
True     19564
Name: count, dtype: int64 /n
AIBen
False    36894
True     28543
Name: count, dtype: int64 /n
AIAcc
False    37302
True     28135
Name: count, dtype: int64 /n
AIComplex
False    37021
True     28416
Name: count, dtype: int64 /n
AIToolCurrently Using
False    35072
True     30365
Name: count, dtype: int64 /n
AIToolInterested in Using
True     34746
False    30691
Name: count, dtype: int64 /n
AIToolNot interested in Using
True     41023
False    24414
Name: count, dtype: int64 /n
AINextMuch more integrated
True     51999
False    13438
Name: count, dtype: int64 /n
AINextNo change
True     52939
False    12498
Name: count, dtype: int64 /n
AINextMore integrated
True     41009
False    24428
Name: count, dtype: int64 /n
AINextLess integrated
True     63082
False     2355
Name: count, dtype: int64 /n
AINextMuch less integrated
True     64289
False     1148
Name: count, dtype: int64 /n
AIThreat
False    44689
True     20748
Name: count, dtype: int64 /n
AIEthics
False    41548
True     23889
Name: count, dtype: int64 /n
AIChallenges
False    37531
True     27906
Name: count, dtype: int64 /n
TBranch
False    44477
True     20960
Name: count, dtype: int64 /n
ICorPM
True     35636
False    29801
Name: count, dtype: int64 /n
WorkExp
True     35779
False    29658
Name: count, dtype: int64 /n
Knowledge_1
True     36773
False    28664
Name: count, dtype: int64 /n
Knowledge_2
True     37416
False    28021
Name: count, dtype: int64 /n
Knowledge_3
True     37342
False    28095
Name: count, dtype: int64 /n
Knowledge_4
True     37407
False    28030
Name: count, dtype: int64 /n
Knowledge_5
True     37557
False    27880
Name: count, dtype: int64 /n
Knowledge_6
True     37573
False    27864
Name: count, dtype: int64 /n
Knowledge_7
True     37659
False    27778
Name: count, dtype: int64 /n
Knowledge_8
True     37679
False    27758
Name: count, dtype: int64 /n
Knowledge_9
True     37802
False    27635
Name: count, dtype: int64 /n
Frequency_1
True     37068
False    28369
Name: count, dtype: int64 /n
Frequency_2
True     37073
False    28364
Name: count, dtype: int64 /n
Frequency_3
True     37727
False    27710
Name: count, dtype: int64 /n
TimeSearching
True     36526
False    28911
Name: count, dtype: int64 /n
TimeAnswering
True     36593
False    28844
Name: count, dtype: int64 /n
Frustration
True     37186
False    28251
Name: count, dtype: int64 /n
ProfessionalTech
True     37673
False    27764
Name: count, dtype: int64 /n
ProfessionalCloud
True     36946
False    28491
Name: count, dtype: int64 /n
ProfessionalQuestion
True     36630
False    28807
Name: count, dtype: int64 /n
Industry
True     36579
False    28858
Name: count, dtype: int64 /n
JobSatPoints_1
True     36113
False    29324
Name: count, dtype: int64 /n
JobSatPoints_4
True     36044
False    29393
Name: count, dtype: int64 /n
JobSatPoints_5
True     36026
False    29411
Name: count, dtype: int64 /n
JobSatPoints_6
True     35987
False    29450
Name: count, dtype: int64 /n
JobSatPoints_7
True     35989
False    29448
Name: count, dtype: int64 /n
JobSatPoints_8
True     35981
False    29456
Name: count, dtype: int64 /n
JobSatPoints_9
True     35981
False    29456
Name: count, dtype: int64 /n
JobSatPoints_10
True     35987
False    29450
Name: count, dtype: int64 /n
JobSatPoints_11
True     35992
False    29445
Name: count, dtype: int64 /n
SurveyLength
False    56182
True      9255
Name: count, dtype: int64 /n
SurveyEase
False    56238
True      9199
Name: count, dtype: int64 /n
ConvertedCompYearly
True     42002
False    23435
Name: count, dtype: int64 /n
JobSat
True     36311
False    29126
Name: count, dtype: int64 /n
EdLevel
False    65437
Name: count, dtype: int64

### Step 6: Normalizing Compensation Data

**Task 4: Normalize Compensation Data Using ConvertedCompYearly**
   1. Use the ConvertedCompYearly column for compensation analysis as the normalized annual compensation is already provided.
   2. Check for missing values in ConvertedCompYearly and handle them if necessary.

In [28]:
## Write your code here

# Replace missing values with the mean
average_value = df["ConvertedCompYearly"].astype("float").mean(axis=0)
df["ConvertedCompYearly"] = df["ConvertedCompYearly"].replace(np.nan, average_value)
missing_CCY = df["ConvertedCompYearly"].isnull()
print(missing_CCY.value_counts())

# Simple feature scaling
df["ConvertedCompYearly"] = df["ConvertedCompYearly"]/df["ConvertedCompYearly"].max()
print(df["ConvertedCompYearly"].unique())

ConvertedCompYearly
False    65437
Name: count, dtype: int64
[0.00529971 0.0004504  0.00184996 ... 0.00096189 0.00059736 0.00718748]

### Step 7: Summary and Next Steps

**In this lab, you focused on identifying and removing duplicate rows.**

- You handled missing values by imputing the most frequent value in a chosen column.

- You used ConvertedCompYearly for compensation normalization and handled missing values.

- For further analysis, consider exploring other columns or visualizing the cleaned dataset.

In [29]:
## Write your code here
df.head(20)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0053,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0053,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,0.0053,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,0.0053,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,0.0053,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,0.0053,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,0.0053,NaN
7,8,I am learning to code,18-24 years old,"Student, full-time;Not employed, but looking f...",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Video-based Online Cou...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,0.0053,NaN
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,0.0053,NaN
9,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,0.0053,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,0.0053,8.0
11,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,0.0053,NaN
12,13,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Sch...,NaN,...,30.0,0.0,0.0,20.0,10.0,10.0,Appropriate in length,Easy,0.0053,8.0
13,14,"I used to be a developer by profession, but no...",35-44 years old,"Not employed, and not looking for work",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Colleague;Other online resources (e.g., videos...",Technical documentation;Blogs;Stack Overflow;I...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,0.0053,NaN
14,15,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Coding sessions (live or record...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,0.0053,NaN
15,16,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,0.0053,5.0
16,17,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,Books / Physical media;Other online resources ...,Technical documentation;Written Tutorials;Stac...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,0.0053,NaN
17,18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,0.0053,NaN
18,19,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Books;Stack Over...,...,60.0,10.0,10.0,0.0,0.0,0.0,Appropriate in length,Easy,0.0053,10.0
19,20,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,0.0053,NaN

<!--
## Change Log

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2024-11-05|1.2|Madhusudhan Moole|Updated lab|
|2024-09-24|1.1|Madhusudhan Moole|Updated lab|
|2024-09-23|1.0|Raghul Ramesh|Created lab|

--!>

Copyright © IBM Corporation. All rights reserved.